import { Product } from "../models/product.model";

export const flashSaleProducts: Product[] = [
  {
    image: "ps",
    title: "HAVIT HV-G92 Gamepad",
    price: "$120",
    oldPrice: "$160",
    rate: 5,
    reviews: 88,
    category: "electronics",
    sale: 30,
  },
  {
    image: "keyboard",
    title: "AK-900 Wired Keyboard",
    price: "$960",
    oldPrice: "$1160",
    rate: 4,
    reviews: 75,
    category: "electronics",
    sale: 20,
  },
  {
    image: "screen",
    title: "IPS LCD Gaming Monitor",
    price: "$370",
    oldPrice: "$400",
    rate: 3.5,
    reviews: 99,
    category: "electronics",
    sale: 25,
  },
  {
    image: "chair",
    title: "S-Series Comfort Chair ",
    price: "$375",
    oldPrice: "$400",
    rate: 4.5,
    reviews: 20,
    category: "home",
    sale: 25,
  },
  {
    image: "jacket",
    title: "The north coat",
    price: "$300",
    oldPrice: "$400",
    rate: 2.5,
    reviews: 50,
    category: "men",
    sale: 25,
  },
];

export const categories = [
  {
    image: "mobile",
    name: "Phones",
  },
  {
    image: "pc",
    name: "Computers",
  },
  {
    image: "watch",
    name: "SmartWatch",
  },
  {
    image: "camera",
    name: "Camera",
  },
  {
    image: "head-phone",
    name: "HeadPhones",
  },
  {
    image: "gaming",
    name: "Gaming",
  },
  {
    image: "camera",
    name: "Camera",
  },
  {
    image: "watch",
    name: "SmartWatch",
  },
];

export const BestSeller: Product[] = [
  {
    image: "jacket",
    title: "The north coat",
    price: "$120",
    oldPrice: "$160",
    rate: 5,
    reviews: 88,
    category: "men",
  },
  {
    image: "bag",
    title: "Gucci duffle bag",
    price: "$960",
    oldPrice: "$1160",
    rate: 4,
    reviews: 75,
    category: "women",
  },
  {
    image: "speaker",
    title: "RGB liquid CPU Cooler",
    price: "$370",
    oldPrice: "$400",
    rate: 3.5,
    reviews: 99,
    category: "electronics",
  },
  {
    image: "table",
    title: "Small BookSelf",
    price: "$375",
    oldPrice: "$400",
    rate: 4.5,
    reviews: 20,
    category: "home",
  },
];

export const Products: Product[] = [
  {
    image: "pet-food",
    title: "Breed Dry Dog Food",
    price: "$120",
    rate: 5,
    reviews: 88,
    category: "pets",
  },
  {
    image: "camers",
    title: "CANON EOS DSLR Camera",
    price: "$960",
    rate: 4,
    reviews: 75,
    category: "electronics",
  },
  {
    image: "lap",
    title: "ASUS FHD Gaming Laptop",
    price: "$1370",
    rate: 4.5,
    reviews: 99,
    category: "electronics",
  },
  {
    image: "car",
    title: "Kids Electric Car",
    price: "$470",
    rate: 4.5,
    reviews: 20,
    category: "kids",
  },
  {
    image: "shoes",
    title: "Jr. Zoom Soccer Cleats",
    price: "$75",
    rate: 4,
    reviews: 20,
    category: "men",
  },
  {
    image: "ps2",
    title: "GP11 Shooter USB Gamepad",
    price: "$75",
    rate: 4,
    reviews: 20,
    category: "electronics",
  },
  {
    image: "jacket2",
    title: "Quilted Satin Jacket",
    price: "$75",
    rate: 4,
    reviews: 20,
    category: "men",
  },
  {
    image: "ps",
    title: "HAVIT HV-G92 Gamepad",
    price: "$120",
    oldPrice: "$160",
    rate: 5,
    reviews: 88,
    category: "electronics",
    sale: 30,
  },
  {
    image: "keyboard",
    title: "AK-900 Wired Keyboard",
    price: "$960",
    oldPrice: "$1160",
    rate: 4,
    reviews: 75,
    category: "electronics",
    sale: 20,
  },
  {
    image: "screen",
    title: "IPS LCD Gaming Monitor",
    price: "$370",
    oldPrice: "$400",
    rate: 3.5,
    reviews: 99,
    category: "electronics",
    sale: 25,
  },
  {
    image: "chair",
    title: "S-Series Comfort Chair ",
    price: "$375",
    oldPrice: "$400",
    rate: 4.5,
    reviews: 20,
    category: "home",
    sale: 25,
  },
  {
    image: "jacket",
    title: "The north coat",
    price: "$300",
    oldPrice: "$400",
    rate: 2.5,
    reviews: 50,
    category: "men",
    sale: 25,
  },
];
